# 公開するページのURL
baseURL = "https://elmetal.github.io/blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "elmetal's blog"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "elmetal"
    bio = "iOS app developer"
    avatar = "img/iconv2.jpg"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#6a5acd"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "el_metal_"
  github = "elmetal"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

